string = str(input())

print(string[2])
print(string[-2])
print(string[0:5])
print(string[0:-2])
print(string[::2])
print(string[1::2])
print(string[-1:0], end="")
print(string[::-1])
print(string[-1::-2])
print(len(string))
